saints_website/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'saints_website'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),

    # Show all topics.
    path('saints/', views.saints, name='saints'),

    # Detail page for a single topic.
    path('saints/<int:saint_id>/', views.saint, name='saint'),

    #search results
    path('saints/search_results/', views.search_results, name='search_results'),

    # prayers
    path('prayers', views.prayers, name='prayers'),

    # calendar
    path('calendar', views.calendar, name='calendar')

]

saints_website/models.py
from django.db import models
import sqlite3
from datetime import date, datetime

from django.db.models.fields import CharField, SlugField

connection = sqlite3.connect("db.sqlite3")

crsr = connection.cursor()

class Saint(models.Model):
    """              """
    text = models.CharField(max_length=200)
    status = models.CharField(max_length=2, default="",blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    birth = models.DateField('birth Y-m-d')
    death = models.DateField('death Y-m-d')
    m_feast = models.CharField(max_length=50)
    d_feast = models.CharField(max_length=2)
    image = models.ImageField()
    cal_Image = models.ImageField()
    thumbnail = models.ImageField()
    credit = models.CharField(max_length=50,blank=True)
    alt = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.text

class Entry(models.Model):

    saint = models.ForeignKey(Saint, on_delete=models.CASCADE)
    text = models.TextField(default="There is nothing listed for this saint.")
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."



class Prayer(models.Model):
    image = models.ImageField()
    prayer = models.ImageField()
    caption = models.CharField(max_length=50,blank=True)
    atl = models.CharField(max_length=50,blank=True)

class Calendar(models.Model):
    month = models.CharField(default=datetime.now(),max_length=50)

saints_website/forms.py
from django import forms

saints_website/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.utils.safestring import mark_safe



from .models import Calendar, Saint, Prayer, Entry
def can_be_coverted(conversion, thing):
    try:
        conversion(thing)
    except:
        return False
    else: 
        return True

def index(request):
    return render(request, 'saints_website/index.html')

def saints(request):
    saints = Saint.objects.order_by('text')
    entries = Entry.objects.order_by('text')
    context = {'saints': saints,'entries':entries}
    return render(request, 'saints_website/saints.html', context)

def saint(request, saint_id):
    saint = Saint.objects.get(id=saint_id)
    entries = saint.entry_set.order_by('-date_added')
    context = {'saint':saint, 'entries':entries}
    return render(request, 'saints_website/saint.html', context)

def search_results(request):
    results = []
    if request.method == "GET":
        query = request.GET.get('q')
        if query == '' or query == None:
            query = 'None'
            results = Saint.objects.filter(Q(text=query))
        elif can_be_coverted(int,query[:4]):
            results = Saint.objects.filter(Q(birth=query) | Q(death=query))
        else:
            results = Saint.objects.filter(Q(text=query))
    return render(request, 'saints_website/search_results.html', {'query': query, 'results': results})

def prayers(request):
    prayers = Prayer.objects.all()
    context = {'prayer':prayers}
    return render(request, 'saints_website/prayers.html', context)

def calendar(request):
    saints = Saint.objects.all()
    year = datetime.now().year
    current_day = str(datetime.now().day)
    
    months = ["","January", "February", "March", "April", "May", "June","July", "August", "September", "October", "November", "December"]
    month_days = ["", 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    current_month = months[datetime.now().month] 
    month_day = []
    image = True
    first_color = 'secondary'
    second_color = 'primary'
    for i in range(month_days[datetime.now().month]):
        month_day.append(f"{i + 1}")
    if request.method == 'POST' and 'run_script' in request.POST: # link view
        from .viewfunctions import toggle
        image = toggle(image)
        first_color = 'primary'
        second_color = 'secondary'
    elif request.method == 'GET' and 'run_script' in request.GET: # picture view
        from .viewfunctions import toggle
        image = False
        image = toggle(image)
        first_color = 'secondary'
        second_color = 'primary'
   
    context = {'saints':saints,'month':current_month, 'days':month_day, 'year':year, 'image_view':image, 'first_color': first_color, 'second_color': second_color, 'current_day': current_day}
    return render(request, 'saints_website/calendar.html', context)

def switch_view(request):
    if request.method != 'POST':
        image = False
    else:
        image = True
    context = {'image_view':image}
    return render(request, 'saints_website/calendar.html', context)

saints_website/templates/saints_website/base.html
<!--/<p>
    <a href="{% url 'saints_website:index' %}">Sain♰s of the Past</a>
    <a href="{% url 'saints_website:saints' %}">Saints</a> 
    <a href="{% url 'saints_website:prayers' %}">Prayers</a> -
    {% if user.is_authenticated %}
        Hello, {{user.username}}.
        <a href="{% url 'users:logout' %}">logout</a>
    {% else %} 
        <a href="{% url 'users:register' %}">register</a> - 
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %} 
    <form action="{% url 'saints_website:search_results' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
</p>


-->
{% load bootstrap4 %} 

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="veiwport" content="width=device-width, initial-scale=1">

        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %} 

    </head>

    <body>

        <!-- Stativ navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                

                <a style ="font-size: 200%;" class="navbar-brand" href="{% url 'saints_website:index' %}">Sain♰s of the Past</a>
                <a class="navbar-brand" href="{% url 'saints_website:saints' %}">Saints</a>
                <a class="navbar-brand" href="{% url 'saints_website:prayers' %}">Prayers</a>
                <a class="navbar-brand" href="{% url 'saints_website:calendar' %}">Calendar</a>

                {% if user.is_authenticated %}
                    <h6><a>Hello, {{ user.username }}.</a></h6>
                    <h6><a class="navbar-brand" href="{% url 'users:logout' %}">log out</a></h6>
                {% else %}
                    <div class="navbar-header">
                        <button type="button" class="btn btn-primary"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                            <a style="color: white;"href="{% url 'users:login' %}">Log in</a>  
                        </button>
                    </div>
                    <h6 id="navbar"><a href="{% url 'users:register' %}">register</a></h6>       
                {% endif %}

                <div class="navbar-brand">
                    <ul class="nav navbar-nav">
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        
                    </ul>

                </div><!--/.nav-collapse -->

            </div>
        </nav>

        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>

        </div> <!-- /container -->
        
    </body>
</html>

saints_website/templates/saints_website/calendar.html
{% extends "saints_website/base.html" %}
{% load custom_tags %}

{% block head %}
<style>
    table {
            margin-left: auto;
            margin-right: auto;
            font-size: 10px;
            width: 100%;
            table-layout:fixed;
    }
  
    td {
            border: 1px solid black;
            text-align: center;
            padding: 10px;
    }
  
</style>
{% endblock head %}

{% block content %}


<form method="post">
    {% csrf_token %}
    <button type="submit" name="run_script" class="btn btn-{{first_color}}">link view</button>
</form>
<form method="get">
    {% csrf_token %}
    <button type="submit" name="run_script" class="btn btn-{{second_color}}">image view</button>
</form>
<!--<script type="text/javascript">
    function toggle(){
        var image_view = "{{ image_view }}"
        if (image_view == "True") {
            image_view = false
        } else if (image_view == "False"){
            image_view == true
        }
        return image_view
        
    }
</script> -->

<!-- VARIABLES -->
{% setvar "148.5px" as WIDTH %}
{% setvar "239.75px" as HEIGHT %}

<table border="1" bordercolor="#00f0c0" cellspacing="0" cellpadding="0" align="center">
    <tbody>
        <tr>
            <td>
                <table  cellspacing="3" cellpadding="3" align="center" border="1" >
                    <tbody>
                        <tr >
                            <td align="center" bgcolor="#00f0c0" width = {{ WIDTH }}> &nbsp;</td>
                            <td colspan="5" align="center" bgcolor="#00f0c0" width = {{ WIDTH }}>
                                <font size="3" face="Tahoma">
                                    <script type="text/javascript">
                                        var monthNames = ["January", "February", "March", "April", "May", "June",
                                            "July", "August", "September", "October", "November", "December"
                                            ];

                                        var d = new Date();
                                        document.write(monthNames[d.getMonth()]," ", d.getFullYear());
                                    </script>
                                </font>
                            </td>
                            <td align="center" bgcolor="#00f0c0">&nbsp;  </td>
                        </tr>
                        <tr >
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Sunday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Monday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Tuesday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Wednesday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Thursday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Friday</b> </font> </td>
                            <td width = {{ WIDTH }}> <font size="3" face="Tahoma"> <b>Saturday</b> </font> </td>
                        </tr>
                        {% for day in days %}
                            {% if day == "1" or day == "8" or day == "15" or day == "22" or day == "29" %}
                                <tr height={{HEIGHT}}>
                            {% endif %}
                            {% if day != "0" %}
                                <td width = {{ WIDTH }} 
                                    {% if day == current_day %}
                                        style="background-color:skyblue"
                                    {% endif %}
                                    >
                                {% for saint in saints %}
                                        {% if saint.m_feast == month %}
                                            {% if day == saint.d_feast %}
                                                {% if  image_view %}
                                                    {% if not image_found %}
                                                        <font size="2" align = "center"> <b>{{saint.d_feast}}</b> </font>
                                                    {% endif %}
                                                    <button type="button" class="btn btn-link">
                                                        <a href="{% url 'saints_website:saint' saint.id %}">
                                                            <img src = "{{ saint.cal_Image.url }}"
                                                            height = "200"
                                                            width = "120" /> 
                                                        </a>
                                                    </button>
                                                    {% setvar True as found %}
                                                    {% setvar True as image_found%}
                                                {% else %}
                                                    {% if not image_found %}
                                                            <font size="2" > <b>{{saint.d_feast}}</b> </font>
                                                        {% endif %}
                                                        <li>
                                                            <font size="2" >
                                                                    <a  class="text-primary" style = "text-decoration: solid;"href="{% url 'saints_website:saint' saint.id %}">{{saint.status}}. {{ saint }}</a>
                                                            </font>
                                                        </li>
                                                    {% setvar True as found %}
                                                    {% setvar True as image_found%}
                                                {% endif %}
                                                
                                            {% elif not image_found%}
                                                <font size="2" > <b>{{day}}</b> </font>
                                                {% setvar True as image_found%}
                                            {% else %}
                                                &nbsp;
                                            {% endif %}
                                        {% elif not image_found %}
                                            <font size="2" > <b>{{day}}</b> </font>
                                            {% setvar True as image_found%}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                {% endfor %}
                                </td>    
                            {% else %}
                                <tr height={{HEIGHT}}>
                            {% endif %}
                        {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
{% endblock content %}
    

saints_website/templates/saints_website/index.html
{% extends "saints_website/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>This is a placeholder.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">register</a> for a placeholder.
    </h2>
    <h2>
        placeholder.
    </h2>
{% endblock content %}

saints_website/templates/saints_website/prayers.html
{% extends "saints_website/base.html" %}

{% block content %}
    {% for prayer in prayers %}
        <figure>
            <img src = "{{ prayer.prayer.url }}"
            height = "{{ prayer.prayer.height }}"
            width = "{{ prayer.prayer.width }}"
            alt = "{{ prayer.alt }}" 
            />
            <figcaption>{{prayer.credit}}</figcaption>
        </figure>
    {% endfor %}

{% endblock content %}

saints_website/templates/saints_website/saint.html
{% extends "saints_website/base.html" %}
{% load custom_tags %}
{% block content %}

    <figure>
        <img src = "{{ saint.image.url }}"
        height = "250"
        width = "150"
        alt = "Picture of Joan of /n Arc" 
        />
        <figcaption>{{saint.credit}}</figcaption>
    </figure>
    
    <pre>{{saint.status}}. {{ saint }}          {{saint.birth}} - {{saint.death}}</pre>
    </br>
    </br>
        {% for entry in entries %}
            {% splice entry.text as paragraphs%}
            {% for paragraph in paragraphs %}
                <p>{{paragraph}}</p>
            {% endfor %}

        {% empty %}
            {% lorem 4 p%}
        {% endfor %}

{% endblock content %}

saints_website/templates/saints_website/saints.html
{% extends "saints_website/base.html" %}
{%load custom_tags%}
{% block content %}
    
    <p>Saints</p>
    
        
        {% setvar True as row %}
        {% for saint in saints %}
            {% if row == True %}
                <main class="container">
                    <div class="row mb-2">
            {% endif %}
            {% toggle row as row %}
            
            
        <!--
            <li>
                <img src = "{{ saint.thumbnail.url }}"
                     height = "50"
                     width = "50"
                     alt = "Picture of Joan of Arc" />
                    <a href="{% url 'saints_website:saint' saint.id %}">{{saint.status}}. {{ saint.text}} - - {{saint.birth}} - {{saint.death}}</a>
                
            </li>
        -->
                        <div class="col-md-6">
                            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <h3 class="mb-0">{{saint.status}}. {{ saint.text}}</h3>
                                <div class="mb-1 text-muted">{{saint.birth}} - {{saint.death}}</div>
                                <p class="card-text mb-auto">
                                    {%for entry in entries%}
                                        {%if entry.saint_id == saint.id%}
                                            {% makeSummary entry.text as summary %}
                                            {{summary}}
                                        {% endif %}
                                    {% empty %}
                                        {% lorem 4 p%}
                                    {% endfor %}
                                    
                                </p>
                                <a href="{% url 'saints_website:saint' saint.id %}" class="stretched-link">Continue reading</a>
                            </div>
                            <div class="col-auto d-none d-lg-block">
                                <img src = "{{ saint.image.url }}"
                                    height = "250"
                                    width = "150"
                                    alt = "Picture of Joan of Arc" />
                            </div>
                            </div>
                        </div>
            
            {% if row == True %}
                    </div>
                </main>
            {% endif %}
        {% empty %}
            <li>No saints have been added yet.</li>
        {% endfor %}
        </div>

{% endblock content %}

saints_website/templates/saints_website/search_results.html
{% extends "saints_website/base.html" %}

{% block content %} 
    <h1>Search</h1>
    
    <ul>
    {% for saint in results %}
        <li>
            <img src = "{{ saint.thumbnail.url }}"
            height = "50"
            width = "50"
            alt = "" />
           <a href="{% url 'saints_website:saint' saint.id %}">{{saint.status}}. {{ saint.text}} - - {{saint.birth}} - {{saint.death}}</a>
        </li>
    {% empty %}
        {% if query == 'None'%}
        {% else %}
            <p>"{{query}}" could not be found. Have a suggestion on a new saint? Please email -----------</p>
            Here are some tips for a succesful search result
            <ul>
                <li>
                    dates should be in YYYY-MM-DD format
                </li>
                <li>
                    when serching up a saint do not include St. or Bl.
                </li>
            </ul>
        {% endif %}
        
    {% endfor %}
    </ul>
{% endblock content %}