users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
	# Login page.
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # Logout page.
    path('logout/',views.logout_view, name='logout'),
    # Registration page.
    path('register/', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('saints_website:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data6=request.POST)

        if form.is_valid():
            new_user = form.save()

            authenticated_user = authenticate(username =new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('saints_website:index'))
    
    context = {'form':form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends "saints_website/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Log in to your Account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}

        <input type="hidden" name="text" value="{% url 'saints_website:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "saints_website/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{form.as_p}}

    <button name="submit" type="button" class="btn btn-primary"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">register</button>
    <input type="hidden" name="text" value="{% url 'saints_website:index' %}" />
    </form>
{% endblock content %}